
export const childViewNames = {
    login: 'login',
    mainGridView: 'mainGridView'
};

export const actionTypes = {
    LOGIN_COMPLETED: 'LOGIN_COMPLETED',
    ERROR_OCCURRED: 'ERROR_OCCURRED',
    CLEAN_ERROR: 'CLEAN_ERROR',
    LOGGED_OUT: 'LOGGED_OUT',
    SHOW_LOGIN_VIEW: 'SHOW_LOGIN_VIEW',
    START_LOADING: 'START_LOADING',
    STOP_LOADING: 'STOP_LOADING',
    CONTAINERS_ARRAY_UPDATED: 'CONTAINERS_ARRAY_UPDATED'
};