export const childViewNames = {
    login: 'login',
    register: 'register',
    resetPassword: 'resetPassword',
    tabView: 'tabView'
};

export const actionTypes = {
    SHOW_REGISTER_VIEW: 'SHOW_REGISTER_VIEW',
    SHOW_RESET_PASSWORD_VIEW: 'SHOW_RESET_PASSWORD_VIEW',
    LOGIN_COMPLETED: 'LOGIN_COMPLETED',
    ERROR_OCCURRED: 'ERROR_OCCURRED',
    LOGGED_OUT: 'LOGGED_OUT',
    SHOW_LOGIN_VIEW: 'SHOW_LOGIN_VIEW',
    START_LOADING: 'START_LOADING',
    STOP_LOADING: 'STOP_LOADING',
    USER_REGISTERED_SUCCESSFULLY: 'USER_REGISTERED_SUCCESSFULLY',
    CREDENTIALS_CHANGED_SUCCESSFULLY: 'CREDENTIALS_CHANGED_SUCCESSFULLY',
    RESET_STATE_FOR_CREDENTIALS: 'RESET_STATE_FOR_CREDENTIALS',
    DELETE_USER_DATA: 'DELETE_USER_DATA',
    NEED_TO_SYNC_ACCOUNT: 'NEED_TO_SYNC_ACCOUNT',
    SYNCHRONIZED_ACCOUNT_SUCCESSFULLY: 'SYNCHRONIZED_ACCOUNT_SUCCESSFULLY'
};